# Generated by Django 6.0.3 on 2026-03-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('entry_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('type', models.CharField(choices=[('JO', 'Journal'), ('OP', 'Opening'), ('AD', 'Adjustment'), ('CL', 'Closing')], default='JO', max_length=2)),
                ('state', models.CharField(choices=[('DR', 'Draft'), ('RE', 'Registered'), ('CA', 'Cancelled')], default='DR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='idx_accounting_entry_date'), models.Index(fields=['state'], name='idx_accounting_entry_state')],
            },
        ),
    ]
