# Generated by Django 6.0.3 on 2026-03-25 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountingEntry', '0001_initial'),
        ('ledgerAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingEntry.accountingentry')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledgerAccount.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Movimiento Contable',
                'verbose_name_plural': 'Movimientos Contables',
                'indexes': [models.Index(fields=['accounting_entry', 'ledger_account'], name='idx_entry_account'), models.Index(fields=['ledger_account'], name='idx_ledger_account')],
            },
        ),
    ]
