# Generated by Django 6.0.3 on 2026-03-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingEntry', '0001_initial'),
        ('accountingMovement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingmovement',
            name='accounting_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='accountingEntry.accountingentry'),
        ),
    ]
